# Setup
title:               Spegman's Every Ref.
description:         'A collection of useful and interesting facts, figures and charts.'
url:                 TODO
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://ibraheemrodrigues.com
  email:             contact@ibraheemrodrigues.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.1.0